language: java
  
jobs:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: linux
      dist: bionic
      jdk: openjdk8
    - os: linux
      dist: bionic
      jdk: openjdk8
      env:
        - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      install:
        - sudo apt-get -y remove default-jdk default-jre default-jdk-headless default-jre-headless ca-certificates-java openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
        - sudo rm -rf /usr/local/lib/jvm
        - sudo apt-get -y update && sudo apt-get -y install openjdk-8-jdk java-common
        - /usr/lib/jvm/java-8-openjdk-amd64/bin/java -version
    - os: osx
      osx_image: xcode9.3

addons:
  sonarcloud:
    organization: "lecousin"
    token:
      secure: gGDNFQVeKAFqKX+GlY7KC/eeJerFLrbosOiM5ZZj9cG82tUOrwI9MAT+eR5RstUVAUtH1oM8Hhi3Gz2egK4YGuodeCO07p0LsWHvcyfAdjPup9p62OmwIuqZY1D8SUo7VYqzMUaLhRyzf57qEEmx0xLyvIZRyj8b5qw29pUxPqnT97bbL2yZ/1KYrgwvpHF5ha+ROLwMcvsXlMhiVIBbWrAfas+F4I3kf7OPDkAxz2bxjPAjeH+QKAliJkXC+dIOxMC8rAq7V3hvCZelQ3begCpnIVadn9Dp/f56NUkhVNUrbtzYh5hpImPQoVvkHrI294BX+TIxtjo6uh6ELlNO1Pjt33NRDAi/FOrVFvjnT8+7bDji/XXA8o0oOX5xpIZeFTk4sAFJtsm+ScSpLIo5KSU29t3Guu8rrqGKL7UW5S3zv3qChhRCF9XjpszZLtKo15uFWIg1a7kYotJsWEI4ooSJEtGB2v1B+cCTZr+KlF6sIY5ATcJNKBBiHonr6Q1jqeoliaDo4zsKvBef7JG0/NX6qwf6CVJl0FgjBc74MlEP2TvJ7eTAnuiYLxi+PHCeOFKS2vuF6MCkT2ulQWkxmfpzCyk9ewWqfVJAwbkygiQcVcbADw8HUp08VwAbGtKYpH7O6qjzeSw/F6Gv37lqH5d0fT0cICVDXgWCg86iDMU=

script:
#- mvn test verify -B
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=lecousin_java-framework-core
- mvn test verify install sonar:sonar -Dsonar.projectKey=lecousin_java-framework-core -Dsonar.projectName=java-framework-core -B 
after_success:
- bash <(curl -s https://codecov.io/bash)
    