language: java

script:
 - mvn test verify -B
# - mvn cobertura:cobertura

after_script:
 - echo _____________CHECKSTYLE______________
 - cat */target/checkstyle-result.xml
 - echo _____________SOPTBUGS______________
 - cat */target/findbugsXml.xml
 
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
 - bash <(curl -s https://codecov.io/bash) -t repository-upload-token
