package net.lecousin.framework;

/** Class to contain the project version generated by Maven. */
public final class LCCoreVersion {

	private LCCoreVersion() { /* no instane */ }
	
	public static final String VERSION = "${project.version}";
	
}
